// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBookPO = "book"

// BookPO mapped from table <book>
type BookPO struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	AuthorID int64  `gorm:"column:author_id;not null" json:"author_id"`
}

// TableName BookPO's table name
func (*BookPO) TableName() string {
	return TableNameBookPO
}
