// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserPO = "user"

// UserPO mapped from table <user>
type UserPO struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	Age  int32  `gorm:"column:age;not null" json:"age"`
}

// TableName UserPO's table name
func (*UserPO) TableName() string {
	return TableNameUserPO
}
